// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class messagecontactStatusAdding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(messagecontactStatusAdding));
        
        string IMigrationMetadata.Id
        {
            get { return "202211161946438_message-contact-StatusAdding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
